services:
  backend:
    image: "${DOCKER_USER}/backend_camphub:latest"
    container_name: backend_camphub
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SQLDB_URL: postgresql+asyncpg://camphub_user:camphub_pass@postgres:5432/camphub_db
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "8000:8000"
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - postgres
    profiles: ["backend"] 
    #สั่งให้ backend run เฉพาะเมื่อ docker compose --profile backend up -d
    #สั่งให้ backend down เฉพาะเมื่อ docker compose --profile backend down
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: camphub_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: camphub_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "9080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: