version: "3.9"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: camphub_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: camphub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
